# Generated by Django 2.2 on 2019-05-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('othello', '0002_delete_kifu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taikyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_black_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to='othello.Player')),
                ('player_white_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to='othello.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Kifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('position', models.IntegerField()),
                ('board_black', models.BigIntegerField()),
                ('board_white', models.BigIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othello.Player')),
                ('taikyoku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othello.Taikyoku')),
            ],
        ),
    ]
