# Generated by Django 2.2 on 2019-05-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0003_kifu_player_taikyoku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kifu',
            name='board_black',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='kifu',
            name='board_white',
            field=models.BinaryField(),
        ),
    ]
