# Generated by Django 2.2 on 2019-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0004_auto_20190506_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kifu',
            name='board_black',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='kifu',
            name='board_white',
            field=models.BigIntegerField(),
        ),
    ]
