# Generated by Django 2.2 on 2019-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0005_auto_20190506_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kifu',
            name='board_black',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kifu',
            name='board_white',
            field=models.BigIntegerField(default=0),
        ),
    ]
