# Generated by Django 2.2 on 2019-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0006_auto_20190506_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kifu',
            old_name='taikyoku_id',
            new_name='taikyoku',
        ),
        migrations.AlterField(
            model_name='kifu',
            name='board_black',
            field=models.BigIntegerField(default=68853694464),
        ),
        migrations.AlterField(
            model_name='kifu',
            name='board_white',
            field=models.BigIntegerField(default=34628173824),
        ),
    ]
